### ISSUE TITLE
Add ability to set an [administrative] "topic" via data tag during embed auto-generation

### ISSUE THREAD

**Issue by patcon** [pol-is/polisServer#6]
For an upcoming launch, I'm planning to integrate pol.is into the webpage of each piece of legislation in Toronto. So there will potentially be hundreds of pol.is conversations created for any legislation page visited.

https://tor-councilmatic-staging.herokuapp.com/search/

It would be nice if there was a way to set the "Topic" (or some similar field) so that something would show up in the "My Conversations" section of the admin interface. It seems the listing will become fairly unnavigable without a good way to set this. @colinmegill suggested a data-* in the iframe like`data-convo-readible-name`.

Thanks! <3

Context: https://meta-pol-is.slack.com/archives/conversations/p1474989317000002

cc: @mbjorkegren

**Comment by mbjorkegren** [comment]
great idea!
I've just pushed out the changes, so it should be working now.
The field is data-topic, and if you don't want that to be visible, you can add data-ucst='false'.
See here:
[https://github.com/colinmegill/polis-documentation/blob/master/usage/PerUserConfig.md](https://github.com/colinmegill/polis-documentation/blob/master/usage/PerUserConfig.md)
and here
[https://github.com/colinmegill/polis-documentation/blob/master/usage/Embedding.md](https://github.com/colinmegill/polis-documentation/blob/master/usage/Embedding.md)

**Comment by patcon** [comment]
Yay! You guys are so effin awesome and responsive

And just my 2c, but it would my sense to me if the data-* tags stayed semantic and self-documenting, rather than favouring cryptic brevity? ie `data-can-vote`, `data-can-write`, `data-show-topic`, `data-show-description`, etc etc

but totally your call :)
