### ISSUE TITLE
Broken seed link in emails

### ISSUE THREAD

**Issue by patcon** [pol-is/polisServer#7]
The "seed" links in the email template don't seem to work anymore:
https://imgur.com/w1bvO7J.png

Tried to find the template in the codebases so I could contrib a fix, but couldn't dig it up. Just so I understand what's possible to contrib as a non-employee, is that in a private repo somewhere?

**Comment by mbjorkegren** [comment]
Great find! I just deployed a fix. The function for that is in server.js it's called "buildSeedUrl".
